#ifdef VENDOR_EDIT
#Jianfeng.Qiu@PSW.MM.AudioDriver.SmartPA, 2018/05/22, Add for tfa98xx
snd-soc-tfa98xx-v6-objs := tfa_container_v6.o tfa98xx_v6.o tfa_dsp_v6.o tfa_init_v6.o
obj-y += snd-soc-tfa98xx-v6.o
#endif /* VENDOR_EDIT */