#ifdef VENDOR_EDIT
#xiang.fei@PSW.MM.AudioDriver.SmartPA, 2017/01/13, Add for tfa9890
snd-soc-tfa98xx-objs := tfa98xx.o tfa_dsp.o tfa_container.o tfa9891_init.o tfa9887_init.o tfa9887B_init.o tfa9888_init.o tfa9890_init.o tfa9897_init.o tfa_debug.o
obj-y += snd-soc-tfa98xx.o
#endif /* VENDOR_EDIT */
